### ISSUE TITLE
Automator2

### ISSUE THREAD

**Issue by vuthelinh** [vuthelinh/selenium-vietnam-training-course#55]
```
C:\Users\Jacob\Downloads\Line\Official\line-app-mobile>mvn clean verify
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.linecorp:line-hybrid-app >--------------------
[INFO] Building Screenplay project with JUnit and Appium 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ line-hybrid-app ---
[INFO] Deleting C:\Users\Jacob\Downloads\Line\Official\line-app-mobile\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ line-hybrid-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Jacob\Downloads\Line\Official\line-app-mobile\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ line-hybrid-app ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ line-hybrid-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ line-hybrid-app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to C:\Users\Jacob\Downloads\Line\Official\line-app-mobile\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ line-hybrid-app ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ line-hybrid-app ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: C:\Users\Jacob\Downloads\Line\Official\line-app-mobile\target\line-hybrid-app-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-failsafe-plugin:2.18.1:integration-test (default) @ line-hybrid-app ---
[INFO] Failsafe report directory: C:\Users\Jacob\Downloads\Line\Official\line-app-mobile\target\failsafe-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Jacob/.m2/repository/org/slf4j/slf4j-simple/1.7.7/slf4j-simple-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Jacob/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
Running serenitybdd.appiumtest.features.WhenUserOpenOXiiStory
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener -

-------------------------------------------------------------------------------------
     _______. _______ .______       _______ .__   __.  __  .___________.____    ____
    /       ||   ____||   _  \     |   ____||  \ |  | |  | |           |\   \  /   /
   |   (----`|  |__   |  |_)  |    |  |__   |   \|  | |  | `---|  |----` \   \/   /
    \   \    |   __|  |      /     |   __|  |  . `  | |  |     |  |       \_    _/
.----)   |   |  |____ |  |\  \----.|  |____ |  |\   | |  |     |  |         |  |
|_______/    |_______|| _| `._____||_______||__| \__| |__|     |__|         |__|

 News and tutorials at http://www.serenity-bdd.info
 Documentation at https://wakaleo.gitbooks.io/the-serenity-book/content/
 Join the Serenity Community on Rocket Chat at https://serenity-bdd.rocket.chat
 Serenity BDD Support and Training at http://serenity-bdd.info/#/trainingandsupport
 Learn Serenity BDD online at http://serenity-dojo.com
-------------------------------------------------------------------------------------

[Appium] Welcome to Appium v1.10.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.10.0"}}
[HTTP] <-- GET /wd/hub/status 200 18 ms - 68
[HTTP]
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener - Test Suite Started: When user open o xii story
[main] INFO net.thucydides.core.steps.ConsoleLoggingListener -
 _____ _____ ____ _____   ____ _____  _    ____ _____ _____ ____
|_   _| ____/ ___|_   _| / ___|_   _|/ \  |  _ \_   _| ____|  _ \
  | | |  _| \___ \ | |   \___ \ | | / _ \ | |_) || | |  _| | | | |
  | | | |___ ___) || |    ___) || |/ ___ \|  _ < | | | |___| |_| |
  |_| |_____|____/ |_|   |____/ |_/_/   \_\_| \_\|_| |_____|____/


TEST STARTED: open_oxii_on_web_view
-------------------------------------------------------------------
[main] INFO net.serenitybdd.core.Serenity - TEST NUMBER: 1
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"C:\\Users\\Jacob\\Downloads\\Line\\binary\\line.apk","appActivity":"jp.naver.line.android.activity.SplashActivity","appPackage":"jp.naver.line.android","noReset":"false","automationName":"uiautomator2","platformName":"Android","deviceName":"5200d8a0ee477597"},"capabilities":{"alwaysMatch":{"appium:app":"C:\\Users\\Jacob\\Downloads\\Line\\binary\\line.apk","appium:appActivity":"jp.naver.line.android.activity.SplashActivity","appium:appPackage":"jp.naver.line.android","appium:automationName":"uiautomator2","appium:deviceName":"5200d8a0ee477597","appium:noReset":"false","platformName":"android"},"firstMatch":[{}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Users\\Jacob\\Downloads\\Line\\binary\\line.apk","appActivity":"jp.naver.line.android.activity.SplashActivity","appPackage":"jp.naver.line.android","noReset":"false","automationName":"uiautomator2","platformName":"Android","deviceName":"5200d8a0ee477597"},null,{"alwaysMatch":{"appium:app":"C:\\Users\\Jacob\\Downloads\\Line\\binary\\line.apk","appium:appActivity":"jp.naver.line.android.activity.SplashActivity","appium:appPackage":"jp.naver.line.android","appium:automationName":"uiautomator2","appium:deviceName":"5200d8a0ee477597","appium:noReset":"false","platformName":"android"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1545800773589 (12:06:13 GMT+0700 (Indochina Time))
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[Appium] Creating new AndroidUiautomator2Driver (v1.26.0) session
[Appium] Capabilities:
[Appium]   platformName: android
[Appium]   app: C:\Users\Jacob\Downloads\Line\binary\line.apk
[Appium]   appActivity: jp.naver.line.android.activity.SplashActivity
[Appium]   appPackage: jp.naver.line.android
[Appium]   automationName: uiautomator2
[Appium]   deviceName: 5200d8a0ee477597
[Appium]   noReset: false
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"app":"C:\\Users\\Jacob\\D... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Session created with session id: 2e06f8f2-5f68-469b-b17a-2e0ffc1e8fe7
(node:17876) [DEP0005] Deprecation[35Warning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allm[BaseDriver] Using local app 'C:\Users\JocUnacob\Downloads\Line\binary\line.apk'
safe(), or Buffer.from() methods instead.
[debug] [UiAutomator2] Checking whether app is actually present
[AndroidDriver] Java version is: 1.8.0_171
[ADB] Checking whether adb is present
[ADB] Found 2 'build-tools' folders under 'C:\Users\Jacob\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:/Users/Jacob/AppData/Local/Android/Sdk/build-tools/28.0.2
[ADB]     C:/Users/Jacob/AppData/Local/Android/Sdk/build-tools/27.0.3
[ADB] Using adb.exe from C:\Users\Jacob\AppData\Local\Android\Sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: 5200d8a0ee477597
[debug] [ADB] Setting device id to 5200d8a0ee477597
[debug] [ADB] Running 'C:\Users\Jacob\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 5200d8a0ee477597 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 26
[debug] [ADB] Device API level: 26
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Running 'C:\Users\Jacob\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 5200d8a0ee477597 shell dumpsys package io.appium.uiautomator2.server'
[debug] [ADB] 'io.appium.uiautomator2.server' is not installed
[debug] [ADB] App 'C:\Users\Jacob\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v3.1.1.apk' is not installed
[debug] [UiAutomator2] io.appium.uiautomator2.server installation state: notInstalled
[debug] [ADB] Checking app cert for C:\Users\Jacob\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v3.1.1.apk
[ADB] Using apksigner.bat from C:\Users\Jacob\AppData\Local\Android\Sdk\build-tools\28.0.2\apksigner.bat
[debug] [ADB] Starting 'C:\Users\Jacob\AppData\Local\Android\Sdk\build-tools\28.0.2\apksigner.bat' with args '["verify","--print-certs","C:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v3.1.1.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[debug] [ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[debug] [ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[debug] [ADB]
[debug] [ADB] 'C:\Users\Jacob\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v3.1.1.apk' is already signed.
[debug] [ADB] Checking app cert for C:\Users\Jacob\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[debug] [ADB] Starting 'C:\Users\Jacob\AppData\Local\Android\Sdk\build-tools\28.0.2\apksigner.bat' with args '["verify","--print-certs","C:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk"]'
[debug] [ADB] apksigner stdout: Signer #1 certificate DN: CN=Android Debug, O=Android, C=US
[debug] [ADB] Signer #1 certificate SHA-256 digest: 3e4f2ab66d641bbbd363421151755f8b12b66ea37a5db43c52116596b7392a8e
[debug] [ADB] Signer #1 certificate SHA-1 digest: e24fc8971c0aad07d1df6cc62af7fb0d48b45b60
[debug] [ADB] Signer #1 certificate MD5 digest: 5623d53469c7f7147b52ace9d09901eb
[debug] [ADB]
[debug] [ADB] 'C:\Users\Jacob\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is signed with non-default certificate
[ADB] Checking whether zipalign is present
[ADB] Using zipalign.exe from C:\Users\Jacob\AppData\Local\Android\Sdk\build-tools\28.0.2\zipalign.exe
[debug] [ADB] C:\Users\Jacob\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is already zip-aligned. Doing nothing
[debug] [ADB] Signing 'C:\Users\Jacob\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' with default cert
[debug] [ADB] Starting 'C:\Users\Jacob\AppData\Local\Android\Sdk\build-tools\28.0.2\apksigner.bat' with args '["sign","--key","C:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8","--cert","C:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem","C:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk"]'
[ADB] Got an error during apksigner execution: Command 'apksigner.bat sign --key C\:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8 --cert C\:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem C\:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk' exited with code 1
[ADB] apksigner stderr: Exception in thread "main" java.nio.file.FileAlreadyExistsException: C:\Users\Jacob\AppData\Local\Temp\apksigner3864390164681272226.apk -> C:\Users\Jacob\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[ADB]   at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:81)
[ADB]   at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[ADB]   at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
[ADB]   at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
[ADB]   at java.nio.file.Files.move(Files.java:1395)
[ADB]   at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
[ADB]   at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
[ADB]
[ADB] Cannot use apksigner tool for signing. Defaulting to sign.jar. Original error: Command 'apksigner.bat sign --key C\:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.pk8 --cert C\:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\keys\\testkey.x509.pem C\:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk' exited with code 1; StdErr: Exception in thread "main" java.nio.file.FileAlreadyExistsException: C:\Users\Jacob\AppData\Local\Temp\apksigner3864390164681272226.apk -> C:\Users\Jacob\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[ADB]   at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:81)
[ADB]   at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[ADB]   at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
[ADB]   at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
[ADB]   at java.nio.file.Files.move(Files.java:1395)
[ADB]   at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:342)
[ADB]   at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
[ADB]
[debug] [ADB] Resigning apk.
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [UiAutomator2] Deleting UiAutomator2 server session
[debug] [JSONWP Proxy] Matched '/' to command name 'deleteSession'
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[debug] [ADB] Running 'C:\Users\Jacob\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 5200d8a0ee477597 shell am force-stop jp.naver.line.android'
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'C:\Users\Jacob\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 5200d8a0ee477597 forward --remove tcp\:8200'
[debug] [ADB] Running 'C:\Users\Jacob\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 5200d8a0ee477597 forward --remove tcp\:8200'
[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command 'C\:\\Users\\Jacob\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 5200d8a0ee477597 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''
[debug] [ADB] Device API level: 26
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1545800782260 (12:06:22 GMT+0700 (Indochina Time))
[debug] [W3C] Encountered internal error running command: Error: Could not sign with default certificate. Original error Command ''C:\\Program Files\\Java\\jdk1.8.0_171\\bin\\java.exe' -jar C\:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\jars\\sign.jar C\:\\Users\\Jacob\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk --override' exited with code 1
[debug] [W3C]     at ADB.apkSigningMethods.signWithDefaultCert (C:\Users\Jacob\AppData\Roaming\npm\node_modules\appium\node_modules\appium-adb\lib\tools\apk-signing.js:124:13)
[HTTP] <-- POST /wd/hub/session 500 8711 ms - 1515
[HTTP]
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener -
           __  _____ _____ ____ _____   _____ _    ___ _     _____ ____
  _       / / |_   _| ____/ ___|_   _| |  ___/ \  |_ _| |   | ____|  _ \
 (_)_____| |    | | |  _| \___ \ | |   | |_ / _ \  | || |   |  _| | | | |
  _|_____| |    | | | |___ ___) || |   |  _/ ___ \ | || |___| |___| |_| |
 (_)     | |    |_| |_____|____/ |_|   |_|/_/   \_\___|_____|_____|____/
          \_\

TEST FAILED WITH ERROR: Open oxii on web view
---------------------------------------------------------------------
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Trader wants to know context view:
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - java.lang.NullPointerException-->null
log4j:WARN No appenders could be found for logger (freemarker.cache).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 22.261 sec <<< FAILURE! - in serenitybdd.appiumtest.features.WhenUserOpenOXiiStory
open_oxii_on_web_view(serenitybdd.appiumtest.features.WhenUserOpenOXiiStory)  Time elapsed: 10.714 sec  <<< ERROR!
net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (It is impossible to create a new session because 'createSession' which takes HttpClient, InputStream and long was not found or it is not accessible
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'VN_LW80999-D', ip: '10.129.142.151', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver
        at com.linecorp.driver.AndroidObject.androidDriver(AndroidObject.java:35)
        at com.linecorp.driver.AndroidObject.getAndroidDriver(AndroidObject.java:30)
        at com.linecorp.interactions.TestAction.<init>(TestAction.java:25)
        at com.linecorp.interactions.TestAction.show(TestAction.java:48)
        at com.linecorp.tasks.Login.performAs(Login.java:50)
        at serenitybdd.appiumtest.features.WhenUserOpenOXiiStory.open_oxii_on_web_view(WhenUserOpenOXiiStory.java:36)


Results :

Tests in error:
  WhenUserOpenOXiiStory.open_oxii_on_web_view:36 » UnsupportedDriver Could not i...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO]
[INFO] --- serenity-maven-plugin:2.0.10:aggregate (serenity-reports) @ line-hybrid-app ---
[INFO] current_project.base.dir: C:\Users\Jacob\Downloads\Line\Official\line-app-mobile
[INFO] Generating test results for 1 tests
[INFO] Loading requirements from tag providers :[net.thucydides.core.requirements.PackageRequirementsTagProvider@7b29cdea, net.thucydides.core.requirements.FileSystemRequirementsTagProvider@3eedd0e3, net.thucydides.core.requirements.FileSystemRequirementsTagProvider@299cab08]
[INFO] 0 requirements loaded after 44 ms
[INFO] 0 related requirements found after 48 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports after 295 ms
[INFO] Configured report threads: 40
[INFO] Test results for 1 tests generated in 1.3 secs
[INFO]
[INFO] --- maven-failsafe-plugin:2.18.1:verify (default) @ line-hybrid-app ---
[INFO] Failsafe report directory: C:\Users\Jacob\Downloads\Line\Official\line-app-mobile\target\failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.700 s
[INFO] Finished at: 2018-12-26T12:06:30+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:verify (default) on project line-hybrid-app: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Jacob\Downloads\Line\Official\line-app-mobile\target\failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by vuthelinh** [comment]
Nếu start Appium server bằng Desktop thì kịch bản có thể chạy. Nhưng không type được

```
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Trader enters 'ngothienphuong@gmail.com' into email field
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Cannot set the element to 'ngothienphuong@gmail.com'. Did you interact with the correct element?
log4j:WARN No appenders could be found for logger (freemarker.cache).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 41.769 sec <<< FAILURE! - in serenitybdd.appiumtest.features.WhenUserOpenOXiiStory
open_oxii_on_web_view(serenitybdd.appiumtest.features.WhenUserOpenOXiiStory)  Time elapsed: 39.705 sec  <<< ERROR!
org.openqa.selenium.InvalidElementStateException: io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Cannot set the element to 'ngothienphuong@gmail.com'. Did you interact with the correct element?
        at io.appium.uiautomator2.handler.SendKeysToElement.safeHandle(SendKeysToElement.java:96)
        at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:37)
        at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:250)
        at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:241)
        at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:764)

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'VN_LW80999-D', ip: '10.129.142.151', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: C:\Users\Jacob\Downloads\Li..., appActivity: jp.naver.line.android.activ..., appPackage: jp.naver.line.android, automationName: uiautomator2, databaseEnabled: false, desired: {app: C:\Users\Jacob\Downloads\Li..., appActivity: jp.naver.line.android.activ..., appPackage: jp.naver.line.android, automationName: uiautomator2, deviceName: 5200d8a0ee477597, hub: http://localhost:4723/wd/hub, locationServicesEnabled: true, nativeWebScreenshot: true, noReset: false, platformName: android, platformVersion: 8.0.0, recreateChromeDriverSessions: true, session-override: true}, deviceApiLevel: 26, deviceManufacturer: samsung, deviceModel: SM-J600G, deviceName: 5200d8a0ee477597, deviceScreenDensity: 320, deviceScreenSize: 720x1480, deviceUDID: 5200d8a0ee477597, hub: http://localhost:4723/wd/hub, javascriptEnabled: true, locationContextEnabled: false, locationServicesEnabled: true, nativeWebScreenshot: true, networkConnectionEnabled: true, noReset: false, pixelRatio: 2, platform: LINUX, platformName: Android, platformVersion: 8.0.0, recreateChromeDriverSessions: true, session-override: true, statBarHeight: 48, takesScreenshot: true, viewportRect: {height: 1336, left: 0, top: 48, width: 720}, warnings: {}, webStorageEnabled: false}
Session ID: ec2abcc1-753a-4dd0-84af-c1f36c9603f3
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'VN_LW80999-D', ip: '10.129.142.151', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
        at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
        at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
        at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
        at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
        at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
        at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
        at com.linecorp.tasks.Login.performAs(Login.java:40)
        at serenitybdd.appiumtest.features.WhenUserOpenOXiiStory.open_oxii_on_web_view(WhenUserOpenOXiiStory.java:36)
```

**Comment by vuthelinh** [comment]
```
public static final Target EMAIL_FIELD = 
			Target.the("email field").located(MobileBy.AndroidUIAutomator("new UiSelector().resourceId(\"jp.naver.line.android:id/text\").text(\"Email address\")"));
	
```
Thay vì dùng 

```
	public static final Target PASSWORD_FIELD = 
			Target.the("password field").located(MobileBy.id("jp.naver.line.android:id/registration_edittext_email"));
```
